{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace | default "cert-manager" }}
type: Opaque
{{- if .Values.secret.stringData }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
{{- if .Values.secret.data }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
{{- end }}
