apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: <your-email>
    server: https://acme-v02.api.letsencrypt.org/directory # production(if use staging https://acme-staging-v02.api.letsencrypt.org/directory)
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: <your-cloudflare-email>
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
