apiVersion: v1
data:
  key.json: <your-base64-encoding-serviceaccount> # cat <your-serviceaccount>.json | base64
kind: Secret
metadata:
  name: clouddns-credentials-secret
  namespace: cert-manager
type: Opaque
